[package]
name = "egui_cable"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.18"
epaint = "0.18"

[dev-dependencies]
eframe = "0.18"
